---
- name: time | install required packages
  apt: pkg=tzdata state=latest

- name: time | adjust timezone
  template: src=time/timezone.j2 dest=/etc/timezone
            owner=root group=root mode=0644
  notify:
    - time | apply timezone change
    - time | restart cron
